name: Deploy to prod server

on:
  push:
    branches:
      - "main"
    paths-ignore:
      - ".github/workflows/**"

jobs:
  deployment:
    runs-on: [self-hosted, hiplet-2973]
    environment: "production"
    steps:
      - name: "Deploy"
        run: |
          cd ${{secrets.PROJECT_PATH}}
          git pull origin main
          sudo -u www-data /bin/bash deploy.sh
